version: '3'

services:
  db:
    image: mysql/mysql-server:8.0
    restart: always
    volumes:
      - .volumes/mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: files
      MYSQL_USER: files
      MYSQL_PASSWORD: files
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: files
      DB_USER: files
      DB_PASSWORD: files
